### PR TITLE
Added newline slurping

### PR DESCRIPTION
**Pull request by szinya**
Hi, I missed this functionality, so decided to add it.

### CODE REVIEW

**Comment by baryshev** [comment]
Can you show example where it can be useful?

**Comment by szinya** [comment]
Sure. I'm compiling templates for later reuse and the new lines each command leaves in the compiled template makes it quite hard to read for humans: e.g. several blank blank lines before the doctype, left there by includes. New line slurping is a feature ported from [EJS](https://github.com/visionmedia/ejs).

**Comment by baryshev** [comment]
Ok, now i see. There are some issues in your realization:

``` js
switch (text.charAt(text.length - 1)) {
  case '-':
    text = text.replace(/-$/, '');
    consumeNextEOL = true;
}
```

`if` will be faster than `switch` in this case. And `text.substr(0, text.length - 1)` will be much more faster than `text.replace(/-$/, '')` because `replace` do string scan.

``` js
.replace('\\n', consumeEOL ? '' : '\\n');
```

This construction replace first newline in next string, but we need to replace newline only from first position. This bug presents in ejs too.

For example:

``` html
<p><% include 'partial1' -%>
<% include 'partial1' -%></p>
<div>
</div>
```

in this case will be rendered as

``` html
<p>partialpartial</p><div>
</div>
```

In version 0.4.6 i added similar but automatically feature. It works like in a `php` now. All new lines removed after template tags but only if newline located immediately after tag.

**Comment by szinya** [comment]
> if will be faster than switch in this case.
> 
> I intentionally used the switch structure so that any other functionallity might be bounded to the last character.
> And text.substr(0, text.length - 1) will be much more faster than text.replace(/-$/, '') because replace do string scan.
> 
> Yes, good point.
> .replace('\n', consumeEOL ? '' : '\n');
> This construction replace first newline in next string, but we need to replace newline only from first position. This bug presents in ejs too.
> 
> I'm aware of that but think that it should be left to the user not to create such structures.
> In version 0.4.6 i added similar but automatically feature. It works like in a php now. All new lines removed after template tags but only if newline located immediately after tag.
> 
> All in all I'm more than happy with it, because this was my first take on the problem, but thought there was some reason behind leaving in those new lines, so I made the change optional. Thanks!

**Pull request closed without merging**
